export const GET_LIST = 'GET_LIST';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_ERROR = 'GET_LIST_ERROR';

export const GET_DETAILS = 'GET_DETAILS';
export const GET_DETAILS_SUCCESS = 'GET_DETAILS_SUCCESS';
export const GET_DETAILS_ERROR = 'GET_DETAILS_ERROR';

export const DELETE_LIST_ITEM = 'DELETE_LIST_ITEM';
export const DELETE_LIST_ITEM_SUCCESS = 'DELETE_LIST_ITEM_SUCCESS';
export const DELETE_LIST_ITEM_ERROR = 'DELETE_LIST_ITEM_ERROR';

export const ADD_LIST_ITEM = 'ADD_LIST_ITEM';
export const ADD_LIST_ITEM_SUCCESS = 'ADD_LIST_ITEM_SUCCESS';
export const ADD_LIST_ITEM_ERROR = 'ADD_LIST_ITEM_ERROR';

export const UPDATE_LIST_ITEM = 'UPDATE_LIST_ITEM';
export const UPDATE_LIST_ITEM_SUCCESS = 'UPDATE_LIST_ITEM_SUCCESS';
export const UPDATE_LIST_ITEM_ERROR = 'UPDATE_LIST_ITEM_ERROR';

export const SEARCH_LIST_ITEM = 'SEARCH_LIST_ITEM';
export const SEARCH_LIST_ITEM_SUCCESS = 'SEARCH_LIST_ITEM_SUCCESS';
export const SEARCH_LIST_ITEM_ERROR = 'SEARCH_LIST_ITEM_ERROR';
