-- Create database with specific name
-- CREATE DATABASE ecommercedashboard; 

-- Schema
-- SERIAL is to increase primary key
-- PRIMARY KEY unique id
-- CREATE TABLE products(
--     prod_id SERIAL PRIMARY KEY,
--     description VARCHAR(255),
--     name VARCHAR(50),
--     quantity,
--     price,
--     image
-- );